[options]
addons_path = /mnt/extra-addons,/mnt/third_party
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$0XqP8V5rLYUQYmyNMSYE4A$4nFdAC1H6B5aqrKeH5LL/q4XK64Sye.tl5BUgP68s9tN.6X4/4QIoAQWduUXoBB/0gMkwyhc15Tm/YYyJcKYsw
db_host = db
db_user = odoo
db_password = odoo

