[options]
addons_path = /mnt/extra-addons,/mnt/third_party
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$izFmbK1VCkHI.T/nfO89Jw$WqZudqL9iPoG0PD4dXaZsAy5a2yXh4xHC7EoH/RvVOvfxN8wPfFE69YWaqKzJSVUXGpMlbzTX8BF3LFnB.Qf3Q
db_host = db
db_user = odoo
db_password = odoo

