[options]
addons_path = /mnt/extra-addons,/mnt/third_party
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$vBfifG/tnZNSipGy1ppT6g$ROxNYIsEv.Ro3tLWVqiEwc6fFc08iq2T5azVnf/ay4ViL7f8y6HT5F1egglXUtAgFBcTbgnH9uNeUovCnsvvmA
db_host = db
db_user = odoo
db_password = odoo

